### ISSUE TITLE
Create a method for installing CLOUDY if it is missing

### ISSUE THREAD

**Issue by rieder** [antonpannekoek/sunbather-fork#3]

**Comment by rieder** [comment]
Currently, this results in an `tarfile.LinkOutsideDestinationError`:
```
>>> import sunbather
Cloudy not found and CLOUDY_PATH is not set. Do you want to install Cloudy 23.01 now in the Sunbather path? (y/n) y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sunbather/src/sunbather/__init__.py", line 37, in <module>
    INSTALLER.extract()
  File "/home/ubuntu/sunbather/src/sunbather/install_cloudy.py", line 52, in extract
    tar.extractall(filter="data")
  File "/usr/lib/python3.10/tarfile.py", line 2278, in extractall
    tarinfo = self._get_extract_tarinfo(member, filter_function, path)
  File "/usr/lib/python3.10/tarfile.py", line 2332, in _get_extract_tarinfo
    self._handle_fatal_error(e)
  File "/usr/lib/python3.10/tarfile.py", line 2330, in _get_extract_tarinfo
    tarinfo = filter_function(tarinfo, path)
  File "/usr/lib/python3.10/tarfile.py", line 819, in data_filter
    new_attrs = _get_filtered_attrs(member, dest_path, True)
  File "/usr/lib/python3.10/tarfile.py", line 806, in _get_filtered_attrs
    raise LinkOutsideDestinationError(member, target_path)
tarfile.LinkOutsideDestinationError: 'c23.01/docs/latex/QuickStart/hazy1.pdf' would link to '/home/ubuntu/sunbather/src/sunbather/hazy1/hazy1.pdf', which is outside the destination
```

**Comment by rieder** [comment]
Requirements (for building Cloudy):
- Make
- Clang

**Comment by rieder** [comment]
> Currently, this results in an `tarfile.LinkOutsideDestinationError`:

Fixed now (by being less strict when extracting the tarfile...)
